# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 04:39
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VoltageSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
