# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 05:27
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab4', '0002_auto_20171002_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voltagesample',
            name='data',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None),
        ),
    ]
