# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab4', '0003_auto_20171002_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voltagesample',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
