# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab4', '0004_auto_20171002_0529'),
    ]

    operations = [
        migrations.AddField(
            model_name='voltagesample',
            name='name',
            field=models.CharField(default='Unspecified', max_length=50),
        ),
    ]
